-- **************************** SqlDBM: MySQL ***************************
-- *** Generated by SqlDBM: AZlegacy modeling by chrysazokly@gmail.com **

-- ************************************** 'database creation'

CREATE DATABASE AZlegacy;
USE AZlegacy;

-- ************************************** `Users`

CREATE TABLE `users`
(
 `user_id`    varchar(128) NOT NULL ,
 `first_name` varchar(45) NOT NULL ,
 `last_name`  varchar(45) NOT NULL ,
 `email`      varchar(100) NOT NULL ,
 `passwd`     varchar(130) NOT NULL ,

PRIMARY KEY (`user_id`)
);

-- ************************************** `Budjet`

CREATE TABLE `budjets`
(
 `budjet_id`        varchar(128) NOT NULL ,
 `timeline`         int NOT NULL ,
 `user_id`          varchar(128) NOT NULL ,
 `total_amount`     float NOT NULL ,

PRIMARY KEY (`budjet_id`),
KEY `FK_1` (`user_id`),
CONSTRAINT `FK_1` FOREIGN KEY `FK_1` (`user_id`) REFERENCES `users` (`user_id`)
);

-- ************************************** `components`

CREATE TABLE `components`
(
 `component_id` varchar(128) NOT NULL ,
 `price`        float NOT NULL ,
 `name`         varchar(50) NOT NULL ,
 `budjet_id_1`  varchar(128) NOT NULL ,

PRIMARY KEY (`component_id`),
KEY `FK_1` (`budjet_id_1`),
CONSTRAINT `FK_4` FOREIGN KEY `FK_1` (`budjet_id_1`) REFERENCES `budjets` (`budjet_id`)
);

-- ************************************** `Posts`

CREATE TABLE `posts`
(
 `Post_id`    varchar(128) NOT NULL ,
 `created_at` datetime NOT NULL ,
 `title`      varchar(100) NOT NULL ,
 `contents`   text NOT NULL ,
 `likes`       int NOT NULL ,
 `dislikes`    int NOT NULL ,
 `views`      int NOT NULL ,
 `user_id`    varchar(128) NOT NULL ,

PRIMARY KEY (`Post_id`),
KEY `FK_1` (`user_id`),
CONSTRAINT `FK_3` FOREIGN KEY `FK_1` (`user_id`) REFERENCES `users` (`user_id`)
);

-- ************************************** `comments`

CREATE TABLE `comments`
(
 `comment_id` varchar(128) NOT NULL ,
 `Post_id`    varchar(128) NOT NULL ,

PRIMARY KEY (`comment_id`, `Post_id`),
KEY `FK_1` (`Post_id`),
CONSTRAINT `FK_5` FOREIGN KEY `FK_1` (`Post_id`) REFERENCES `posts` (`Post_id`)
);

-- ************************************** `Side_hustle`

CREATE TABLE `side_hustles`
(
 `side_hustle_id`      varchar(128) NOT NULL ,
 `title`               varchar(100) NOT NULL ,
 `steps`               text NOT NULL ,
 `deadline`            date NOT NULL ,
 `initial_investement` float NOT NULL ,
 `estimated_return`    float NOT NULL ,
 `user_id`             varchar(128) NOT NULL ,

PRIMARY KEY (`side_hustle_id`),
KEY `FK_1` (`user_id`),
CONSTRAINT `FK_2` FOREIGN KEY `FK_1` (`user_id`) REFERENCES `users` (`user_id`)
);


